---
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(levelname)-8s %(name)-48s %(message)s'
  extended:
    format: '%(asctime)s %(levelname)-8s %(name)s(%(funcName)s:%(lineno)d) - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  dp_info_file:
    () : __main__.dp_infologger
    level: INFO
    formatter: extended

  dp_debug_file:
    () : __main__.dp_debugger
    level: DEBUG
    formatter: extended

loggers:
  deathpledge:
    level: DEBUG
    handlers: [dp_info_file, dp_debug_file, debug_console]
    propagate: no
  deathpledge.database:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: NOTSET
  handlers: [console]
